# Generated by Django 3.1.4 on 2020-12-08 22:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
