# Generated by Django 3.1.4 on 2020-12-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_routine_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='repeat',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='repeat',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
