# Generated by Django 3.1.4 on 2020-12-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20201208_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
